pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo "Hello Razan! Jenkinsfile is working 🎉"
            }
        }
        stage('Build') {
            steps {
                echo "Building Flask App..."
            }
        }
    }
}
