pipeline {
    agent any

    stages {
        stage('Checkout Source') {
            steps {
                // This ensures the full repo is cloned into the workspace
                checkout scm
                echo " Source code checked out successfully"
            }
        }

        stage('Check') {
            steps {
                echo "Hello Razan! Jenkinsfile is running 🚀"
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t flask-ci-cd-app .'
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    // Stop & remove any running container with same name
                    sh 'docker rm -f flask-ci-cd-container || true'
                    sh 'docker run -d -p 5000:5000 --name flask-ci-cd-container flask-ci-cd-app'
                }
            }
        }
    }
}
