pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/razanmujawar2211-create/ci-cd-flask-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo "Building Docker image..."
                    sh 'docker build -t flask-ci-cd-app .'
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    echo "Running container..."
                    sh 'docker rm -f flask-ci-cd-container || true'
                    sh 'docker run -d -p 5000:5000 --name flask-ci-cd-container flask-ci-cd-app'
                }
            }
        }
    }
}
