pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "flask-ci-cd"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install dependencies') {
            steps {
                dir('CI-CD pipeline') {
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('SonarQube Analysis') {
            environment {
                SCANNER_HOME = tool 'SonarQubeScanner'
            }
            steps {
                dir('CI-CD pipeline') {
                    withSonarQubeEnv('MySonarQubeServer') {
                        sh """
                            ${SCANNER_HOME}/bin/sonar-scanner \
                            -Dsonar.projectKey=flask-ci-cd \
                            -Dsonar.sources=. \
                            -Dsonar.host.url=http://localhost:9000 \
                            -Dsonar.login=${SONAR_AUTH_TOKEN}
                        """
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('CI-CD pipeline') {
                    sh "docker build -t ${DOCKER_IMAGE} ."
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                sh "docker rm -f flask-app || true"   // stop if already running
                sh "docker run -d -p 5000:5000 --name flask-app ${DOCKER_IMAGE}"
            }
        }
    }
}
