pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Clone repo
                git 'https://github.com/razanmujawar2211-create/ci-cd-flask-app.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                echo 'SonarQube analysis placeholder - will integrate later'
            }
        }

        stage('Build Docker Image') {
            steps {
                // Build from current directory since Dockerfile is in root
                bat "docker build -t flask-ci-cd:latest ."
            }
        }

        stage('Push Docker Image') {
            steps {
                echo 'Skipping DockerHub push for now - will add later'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                echo 'Skipping Kubernetes deploy for now - will add later'
            }
        }
    }
}
