pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/razanmujawar2211-create/ci-cd-flask-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat "docker build -t flask-ci-cd:latest ./app"
            }
        }
    }
}
